set_property PACKAGE_PIN U13 [get_ports {led_id[7]}]
set_property PACKAGE_PIN K2 [get_ports {led_id[6]}]
set_property PACKAGE_PIN T14 [get_ports {led_id[5]}]
set_property PACKAGE_PIN P14 [get_ports {led_id[4]}]
set_property PACKAGE_PIN J14 [get_ports {led_id[3]}]
set_property PACKAGE_PIN T9 [get_ports {led_id[2]}]
set_property PACKAGE_PIN J18 [get_ports {led_id[1]}]
set_property PACKAGE_PIN J17 [get_ports {led_id[0]}]
set_property PACKAGE_PIN T10 [get_ports {out_led[7]}]
set_property PACKAGE_PIN R10 [get_ports {out_led[6]}]
set_property PACKAGE_PIN K16 [get_ports {out_led[5]}]
set_property PACKAGE_PIN K13 [get_ports {out_led[4]}]
set_property PACKAGE_PIN P15 [get_ports {out_led[3]}]
set_property PACKAGE_PIN T11 [get_ports {out_led[2]}]
set_property PACKAGE_PIN L18 [get_ports {out_led[1]}]
set_property PACKAGE_PIN H15 [get_ports {out_led[0]}]
set_property PACKAGE_PIN R15 [get_ports a1]
set_property PACKAGE_PIN M13 [get_ports a2]
set_property PACKAGE_PIN L16 [get_ports a3]
set_property PACKAGE_PIN J15 [get_ports a4]
set_property IOSTANDARD LVCMOS33 [get_ports {led_id[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_id[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_id[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_id[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_id[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_id[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_id[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_id[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out_led[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out_led[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out_led[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out_led[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out_led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out_led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out_led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out_led[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports a1]
set_property IOSTANDARD LVCMOS33 [get_ports a2]
set_property IOSTANDARD LVCMOS33 [get_ports a3]
set_property IOSTANDARD LVCMOS33 [get_ports a4]

set_property PACKAGE_PIN R13 [get_ports b1]
set_property PACKAGE_PIN U18 [get_ports b2]
set_property PACKAGE_PIN T18 [get_ports b3]
set_property PACKAGE_PIN R17 [get_ports b4]
set_property IOSTANDARD LVCMOS33 [get_ports b1]
set_property IOSTANDARD LVCMOS33 [get_ports b2]
set_property IOSTANDARD LVCMOS33 [get_ports b3]
set_property IOSTANDARD LVCMOS33 [get_ports b4]

set_property PACKAGE_PIN H17 [get_ports over]
set_property IOSTANDARD LVCMOS33 [get_ports over]

set_property PACKAGE_PIN E3 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]

set_property PACKAGE_PIN U8 [get_ports cin]
set_property IOSTANDARD LVCMOS33 [get_ports cin]

#set_property PACKAGE_PIN T8 [get_ports whetherAdd]
#set_property IOSTANDARD LVCMOS33 [get_ports whetherAdd]

#set_property IOSTANDARD LVCMOS33 [get_ports underZ]
#set_property PACKAGE_PIN K15 [get_ports underZ]

set_property IOSTANDARD LVCMOS33 [get_ports whetherAdd]

set_property PACKAGE_PIN U11 [get_ports whetherAdd]
